//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Comment.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class House_Info
    {
        public int HouseId { get; set; }
        public string LandlordName { get; set; }
        public string HouseName { get; set; }
        public bool HouseStatus { get; set; }
        public int AreaCode { get; set; }
        public string Community { get; set; }
        public string Building { get; set; }
        public Nullable<int> Unit { get; set; }
        public int RoomNumber { get; set; }
        public string Toward { get; set; }
        public string HouseType { get; set; }
        public int AreaSize { get; set; }
        public string DegreeOfDecoration { get; set; }
        public double MonthlyRcnt { get; set; }
        public System.DateTime CreateDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public bool DeleteStatus { get; set; }
    }
}
