//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Comment.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RentHouseEntities : DbContext
    {
        public RentHouseEntities()
            : base("name=RentHouseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<User_Info> User_Info { get; set; }
        public virtual DbSet<Tenants_Info> Tenants_Info { get; set; }
        public virtual DbSet<Area_Info> Area_Info { get; set; }
        public virtual DbSet<House_Info> House_Info { get; set; }
    }
}
